-- iDART data check (read-only)
--
-- Looks for data that older iDART versions could leave behind and that
-- stops iDART 3.9.0 opening a record or a screen. It is a single SELECT
-- statement, so it only reads and changes nothing.
--
-- pgAdmin: right-click the database iDART uses (for example pharm_migrated)
-- and choose Query Tool. Open this file with the folder button, press
-- Ctrl+A and then F5 (with only part of the text selected, F5 runs just
-- that part).
--
-- Or from PowerShell, in the folder with this file (18 is your PostgreSQL
-- version):
--
--   & "C:\Program Files\PostgreSQL\18\bin\psql.exe" -h localhost -U postgres -d pharm_migrated -f idart-data-check.sql -o idart-data-check-output.txt
--
-- Every row shows found = 0 when the data is fine. For the others,
-- details shows how many records are affected and a few examples. Rows
-- marked "(3.9.0 copes)" are only for information: iDART 3.9.0 works with
-- them.

select item as "check", found, coalesce(details, '') as details from (
select 1 as n, 'packages with blank values' as item, (count(*) filter (where "modified" is null or "weekssupply" is null or "stockreturned" is null or "packagereturned" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "modified" is null) > 0 then 'modified: ' || count(*) filter (where "modified" is null) end, case when count(*) filter (where "weekssupply" is null) > 0 then 'weekssupply: ' || count(*) filter (where "weekssupply" is null) end, case when count(*) filter (where "stockreturned" is null) > 0 then 'stockreturned: ' || count(*) filter (where "stockreturned" is null) end, case when count(*) filter (where "packagereturned" is null) > 0 then 'packagereturned: ' || count(*) filter (where "packagereturned" is null) end) as details from "package"
union all
select 2 as n, 'drugs in packages with blank values' as item, (count(*) filter (where "amount" is null or "modified" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "amount" is null) > 0 then 'amount: ' || count(*) filter (where "amount" is null) end, case when count(*) filter (where "modified" is null) > 0 then 'modified: ' || count(*) filter (where "modified" is null) end) as details from "packageddrugs"
union all
select 3 as n, 'patients with blank values' as item, (count(*) filter (where "modified" is null or "sex" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "modified" is null) > 0 then 'modified: ' || count(*) filter (where "modified" is null) end, case when count(*) filter (where "sex" is null) > 0 then 'sex: ' || count(*) filter (where "sex" is null) end) as details from "patient"
union all
select 4 as n, 'prescriptions with blank values' as item, (count(*) filter (where "clinicalstage" is null or "current" is null or "date" is null or "duration" is null or "modified" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "clinicalstage" is null) > 0 then 'clinicalstage: ' || count(*) filter (where "clinicalstage" is null) end, case when count(*) filter (where "current" is null) > 0 then 'current: ' || count(*) filter (where "current" is null) end, case when count(*) filter (where "date" is null) > 0 then 'date: ' || count(*) filter (where "date" is null) end, case when count(*) filter (where "duration" is null) > 0 then 'duration: ' || count(*) filter (where "duration" is null) end, case when count(*) filter (where "modified" is null) > 0 then 'modified: ' || count(*) filter (where "modified" is null) end) as details from "prescription"
union all
select 5 as n, 'drugs on prescriptions with blank values' as item, (count(*) filter (where "timesperday" is null or "modified" is null or "amtpertime" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "timesperday" is null) > 0 then 'timesperday: ' || count(*) filter (where "timesperday" is null) end, case when count(*) filter (where "modified" is null) > 0 then 'modified: ' || count(*) filter (where "modified" is null) end, case when count(*) filter (where "amtpertime" is null) > 0 then 'amtpertime: ' || count(*) filter (where "amtpertime" is null) end) as details from "prescribeddrugs"
union all
select 6 as n, 'drugs with blank values' as item, (count(*) filter (where "name" is null or "modified" is null or "packsize" is null or "sidetreatment" is null or "defaultamnt" is null or "defaulttimes" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "name" is null) > 0 then 'name: ' || count(*) filter (where "name" is null) end, case when count(*) filter (where "modified" is null) > 0 then 'modified: ' || count(*) filter (where "modified" is null) end, case when count(*) filter (where "packsize" is null) > 0 then 'packsize: ' || count(*) filter (where "packsize" is null) end, case when count(*) filter (where "sidetreatment" is null) > 0 then 'sidetreatment: ' || count(*) filter (where "sidetreatment" is null) end, case when count(*) filter (where "defaultamnt" is null) > 0 then 'defaultamnt: ' || count(*) filter (where "defaultamnt" is null) end, case when count(*) filter (where "defaulttimes" is null) > 0 then 'defaulttimes: ' || count(*) filter (where "defaulttimes" is null) end) as details from "drug"
union all
select 7 as n, 'stock batches with blank values' as item, (count(*) filter (where "modified" is null or "unitsreceived" is null or "hasunitsremaining" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "modified" is null) > 0 then 'modified: ' || count(*) filter (where "modified" is null) end, case when count(*) filter (where "unitsreceived" is null) > 0 then 'unitsreceived: ' || count(*) filter (where "unitsreceived" is null) end, case when count(*) filter (where "hasunitsremaining" is null) > 0 then 'hasunitsremaining: ' || count(*) filter (where "hasunitsremaining" is null) end) as details from "stock"
union all
select 8 as n, 'stock adjustments with blank values' as item, (count(*) filter (where "stockcount" is null or "adjustedvalue" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "stockcount" is null) > 0 then 'stockcount: ' || count(*) filter (where "stockcount" is null) end, case when count(*) filter (where "adjustedvalue" is null) > 0 then 'adjustedvalue: ' || count(*) filter (where "adjustedvalue" is null) end) as details from "stockadjustment"
union all
select 9 as n, 'stock takes with blank values' as item, (count(*) filter (where "open" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "open" is null) > 0 then 'open: ' || count(*) filter (where "open" is null) end) as details from "stocktake"
union all
select 10 as n, 'pharmacies (stock centres) with blank values' as item, (count(*) filter (where "preferred" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "preferred" is null) > 0 then 'preferred: ' || count(*) filter (where "preferred" is null) end) as details from "stockcenter"
union all
select 11 as n, 'clinics with blank values' as item, (count(*) filter (where "mainclinic" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "mainclinic" is null) > 0 then 'mainclinic: ' || count(*) filter (where "mainclinic" is null) end) as details from "clinic"
union all
select 12 as n, 'doctors with blank values' as item, (count(*) filter (where "modified" is null or "active" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "modified" is null) > 0 then 'modified: ' || count(*) filter (where "modified" is null) end, case when count(*) filter (where "active" is null) > 0 then 'active: ' || count(*) filter (where "active" is null) end) as details from "doctor"
union all
select 13 as n, 'regimens with blank values' as item, (count(*) filter (where "modified" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "modified" is null) > 0 then 'modified: ' || count(*) filter (where "modified" is null) end) as details from "regimen"
union all
select 14 as n, 'drugs in regimens with blank values' as item, (count(*) filter (where "timesperday" is null or "modified" is null or "amtpertime" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "timesperday" is null) > 0 then 'timesperday: ' || count(*) filter (where "timesperday" is null) end, case when count(*) filter (where "modified" is null) > 0 then 'modified: ' || count(*) filter (where "modified" is null) end, case when count(*) filter (where "amtpertime" is null) > 0 then 'amtpertime: ' || count(*) filter (where "amtpertime" is null) end) as details from "regimendrugs"
union all
select 15 as n, 'pregnancies with blank values' as item, (count(*) filter (where "modified" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "modified" is null) > 0 then 'modified: ' || count(*) filter (where "modified" is null) end) as details from "pregnancy"
union all
select 16 as n, 'users with blank values' as item, (count(*) filter (where "modified" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "modified" is null) > 0 then 'modified: ' || count(*) filter (where "modified" is null) end) as details from "users"
union all
select 17 as n, 'transaction log entries with blank values' as item, (count(*) filter (where "modified" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "modified" is null) > 0 then 'modified: ' || count(*) filter (where "modified" is null) end) as details from "logging"
union all
select 18 as n, 'drug strengths with blank values' as item, (count(*) filter (where "strength" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "strength" is null) > 0 then 'strength: ' || count(*) filter (where "strength" is null) end) as details from "chemicaldrugstrength"
union all
select 19 as n, 'identifier types with blank values' as item, (count(*) filter (where "index" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "index" is null) > 0 then 'index: ' || count(*) filter (where "index" is null) end) as details from "identifiertype"
union all
select 20 as n, 'old patient numbers with blank values' as item, (count(*) filter (where "masterpatientid" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "masterpatientid" is null) > 0 then 'masterpatientid: ' || count(*) filter (where "masterpatientid" is null) end) as details from "alternatepatientidentifier"
union all
select 21 as n, 'deleted-item records with blank values' as item, (count(*) filter (where "deleteditemid" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "deleteditemid" is null) > 0 then 'deleteditemid: ' || count(*) filter (where "deleteditemid" is null) end) as details from "deleteditem"
union all
select 22 as n, 'label print records with blank values' as item, (count(*) filter (where "dispensedqty" is null or "stockid" is null or "timesperday" is null or "numberoflabels" is null or "sidetreatment" is null or "packageindex" is null or "weekssupply" is null or "invalid" is null or "prescriptionduration" is null or "senttoekapa" is null or "dispensedforlaterpickup" is null or "firstbatchinprintjob" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "dispensedqty" is null) > 0 then 'dispensedqty: ' || count(*) filter (where "dispensedqty" is null) end, case when count(*) filter (where "stockid" is null) > 0 then 'stockid: ' || count(*) filter (where "stockid" is null) end, case when count(*) filter (where "timesperday" is null) > 0 then 'timesperday: ' || count(*) filter (where "timesperday" is null) end, case when count(*) filter (where "numberoflabels" is null) > 0 then 'numberoflabels: ' || count(*) filter (where "numberoflabels" is null) end, case when count(*) filter (where "sidetreatment" is null) > 0 then 'sidetreatment: ' || count(*) filter (where "sidetreatment" is null) end, case when count(*) filter (where "packageindex" is null) > 0 then 'packageindex: ' || count(*) filter (where "packageindex" is null) end, case when count(*) filter (where "weekssupply" is null) > 0 then 'weekssupply: ' || count(*) filter (where "weekssupply" is null) end, case when count(*) filter (where "invalid" is null) > 0 then 'invalid: ' || count(*) filter (where "invalid" is null) end, case when count(*) filter (where "prescriptionduration" is null) > 0 then 'prescriptionduration: ' || count(*) filter (where "prescriptionduration" is null) end, case when count(*) filter (where "senttoekapa" is null) > 0 then 'senttoekapa: ' || count(*) filter (where "senttoekapa" is null) end, case when count(*) filter (where "dispensedforlaterpickup" is null) > 0 then 'dispensedforlaterpickup: ' || count(*) filter (where "dispensedforlaterpickup" is null) end, case when count(*) filter (where "firstbatchinprintjob" is null) > 0 then 'firstbatchinprintjob: ' || count(*) filter (where "firstbatchinprintjob" is null) end) as details from "packagedruginfotmp"
union all
select 23 as n, 'SMS campaigns with blank values' as item, (count(*) filter (where "duration" is null or "timesperday" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "duration" is null) > 0 then 'duration: ' || count(*) filter (where "duration" is null) end, case when count(*) filter (where "timesperday" is null) > 0 then 'timesperday: ' || count(*) filter (where "timesperday" is null) end) as details from "campaign"
union all
select 24 as n, 'SMS schedules with blank values' as item, (count(*) filter (where "messagenumber" is null or "daystoschedule" is null or "scheduledsuccessfully" is null or "senttoalerts" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "messagenumber" is null) > 0 then 'messagenumber: ' || count(*) filter (where "messagenumber" is null) end, case when count(*) filter (where "daystoschedule" is null) > 0 then 'daystoschedule: ' || count(*) filter (where "daystoschedule" is null) end, case when count(*) filter (where "scheduledsuccessfully" is null) > 0 then 'scheduledsuccessfully: ' || count(*) filter (where "scheduledsuccessfully" is null) end, case when count(*) filter (where "senttoalerts" is null) > 0 then 'senttoalerts: ' || count(*) filter (where "senttoalerts" is null) end) as details from "messageschedule"
union all
select 25 as n, 'patient statistics with blank values' as item, (count(*) filter (where "entry_id" is null or "patient_id" is null or "patientstattype_id" is null or "statnumeric" is null))::bigint as found, concat_ws(', ', case when count(*) filter (where "entry_id" is null) > 0 then 'entry_id: ' || count(*) filter (where "entry_id" is null) end, case when count(*) filter (where "patient_id" is null) > 0 then 'patient_id: ' || count(*) filter (where "patient_id" is null) end, case when count(*) filter (where "patientstattype_id" is null) > 0 then 'patientstattype_id: ' || count(*) filter (where "patientstattype_id" is null) end, case when count(*) filter (where "statnumeric" is null) > 0 then 'statnumeric: ' || count(*) filter (where "statnumeric" is null) end) as details from "patientstatistic"
union all
select 26 as n, 'patient visits with no visit reason' as item, (count(*) filter (where "patientvisitreason_id" is null))::bigint as found, null as details from "patientvisit"
union all
select 27 as n, 'main clinic missing or more than one' as item, ((select case when count(*) = 1 then 0 else greatest(count(*), 1) end from clinic where mainclinic))::bigint as found, (select case when count(*) = 0 then 'no clinic is marked as the main clinic' when count(*) > 1 then string_agg(clinicname, ', ') end from clinic where mainclinic) as details 
union all
select 28 as n, 'clinic names that differ only in capitals' as item, ((select count(*) from (select 1 from clinic group by upper(clinicname) having count(*) > 1) d))::bigint as found, (select string_agg(n, ', ') from (select string_agg(clinicname, ' / ') n from clinic group by upper(clinicname) having count(*) > 1 limit 5) d) as details 
union all
select 29 as n, 'pharmacy names that differ only in capitals' as item, ((select count(*) from (select 1 from stockcenter group by upper(stockcentername) having count(*) > 1) d))::bigint as found, (select string_agg(n, ', ') from (select string_agg(stockcentername, ' / ') n from stockcenter group by upper(stockcentername) having count(*) > 1 limit 5) d) as details 
union all
select 30 as n, 'more than one preferred pharmacy' as item, ((select case when count(*) > 1 then count(*) else 0 end from stockcenter where preferred))::bigint as found, (select case when count(*) > 1 then string_agg(stockcentername, ', ') end from stockcenter where preferred) as details 
union all
select 31 as n, 'more than one open stock take' as item, ((select case when count(*) > 1 then count(*) else 0 end from stocktake where open))::bigint as found, (select case when count(*) > 1 then string_agg(coalesce(stocktakenumber, id::text), ', ') end from stocktake where open) as details 
union all
select 32 as n, 'patients with more than one open pregnancy' as item, ((select count(*) from (select 1 from pregnancy where enddate is null group by patient having count(*) > 1) d))::bigint as found, (select string_agg(p.patientid, ', ') from (select patient from pregnancy where enddate is null group by patient having count(*) > 1 limit 5) d join patient p on p.id = d.patient) as details 
union all
select 33 as n, 'patient numbers used by more than one patient' as item, ((select count(*) from (select 1 from patient group by upper(patientid) having count(*) > 1) d))::bigint as found, (select string_agg(n, ', ') from (select min(patientid) n from patient group by upper(patientid) having count(*) > 1 order by 1 limit 5) d) as details 
union all
select 34 as n, 'drug names used by more than one drug' as item, ((select count(*) from (select 1 from drug group by name having count(*) > 1) d))::bigint as found, (select string_agg(n, ', ') from (select name n from drug group by name having count(*) > 1 order by 1 limit 5) d) as details 
union all
select 35 as n, 'usernames used by more than one user' as item, ((select count(*) from (select 1 from users group by upper(cl_username) having count(*) > 1) d))::bigint as found, (select string_agg(n, ', ') from (select min(cl_username) n from users group by upper(cl_username) having count(*) > 1 order by 1 limit 5) d) as details 
union all
select 36 as n, 'package IDs used by more than one package (3.9.0 copes)' as item, ((select count(*) from (select 1 from package group by packageid having count(*) > 1) d))::bigint as found, (select string_agg(n, ', ') from (select packageid n from package group by packageid having count(*) > 1 order by 1 limit 5) d) as details 
union all
select 37 as n, 'packages whose prescription is missing' as item, ((select count(*) from package k where k.prescription is not null and not exists (select 1 from prescription r where r.id = k.prescription)))::bigint as found, (select string_agg(packageid, ', ') from (select packageid from package k where k.prescription is not null and not exists (select 1 from prescription r where r.id = k.prescription) order by 1 limit 5) d) as details 
union all
select 38 as n, 'stock adjustments whose stock batch is missing' as item, ((select count(*) from stockadjustment a where not exists (select 1 from stock s where s.id = a.stock)))::bigint as found, (select string_agg(id::text, ', ') from (select a.id from stockadjustment a where not exists (select 1 from stock s where s.id = a.stock) order by 1 limit 5) d) as details 
union all
select 39 as n, 'accumulated drugs whose package is missing' as item, ((select count(*) from accumulateddrugs a where a.withpackage is not null and not exists (select 1 from package k where k.id = a.withpackage)))::bigint as found, (select string_agg(id::text, ', ') from (select a.id from accumulateddrugs a where a.withpackage is not null and not exists (select 1 from package k where k.id = a.withpackage) order by 1 limit 5) d) as details 
union all
select 40 as n, 'transaction log entries whose user is missing' as item, ((select count(*) from logging l where l.idart_user is not null and not exists (select 1 from users u where u.id = l.idart_user)))::bigint as found, (select string_agg(id::text, ', ') from (select l.id from logging l where l.idart_user is not null and not exists (select 1 from users u where u.id = l.idart_user) order by 1 limit 5) d) as details 
union all
select 41 as n, 'prescriptions with no doctor' as item, ((select count(*) from prescription where doctor is null))::bigint as found, (select concat_ws('; ', case when count(*) filter (where r."current" = 'T') > 0 then count(*) filter (where r."current" = 'T') || ' of them current' end, 'patients: ' || (select string_agg(n, ', ') from (select distinct p.patientid n from prescription r2 join patient p on p.id = r2.patient where r2.doctor is null order by 1 limit 5) x)) from prescription r where r.doctor is null) as details 
union all
select 42 as n, 'drugs on prescriptions with no drug' as item, ((select count(*) from prescribeddrugs where drug is null))::bigint as found, ('patients: ' || (select string_agg(n, ', ') from (select distinct p.patientid n from prescribeddrugs pd join prescription r on r.id = pd.prescription join patient p on p.id = r.patient where pd.drug is null order by 1 limit 5) x)) as details 
union all
select 43 as n, 'drug forms with blank label wording' as item, ((select count(*) from form where formlanguage1 is null))::bigint as found, (select string_agg(coalesce(n, '(no name)'), ', ') from (select form n from form where formlanguage1 is null order by 1 limit 5) x) as details 
union all
select 44 as n, 'patient visits with no patient (3.9.0 copes)' as item, ((select count(*) from patientvisit where patient_id is null))::bigint as found, (select case when count(*) > 0 then count(dateofvisit) || ' with a date' end from patientvisit where patient_id is null) as details 
union all
select 45 as n, 'patients whose episode order has gaps' as item, ((select count(*) from (select patient from episode where patient is not null group by patient having count("index") <> count(*) or min("index") <> 0 or max("index") <> count(*) - 1 or count(distinct "index") <> count(*)) x))::bigint as found, (select string_agg(n, ', ') from (select max(p.patientid) n from episode t join patient p on p.id = t.patient group by t.patient having count(t."index") <> count(*) or min(t."index") <> 0 or max(t."index") <> count(*) - 1 or count(distinct t."index") <> count(*) order by 1 limit 5) x) as details 
union all
select 46 as n, 'prescriptions whose drug order has gaps' as item, ((select count(*) from (select prescription from prescribeddrugs where prescription is not null group by prescription having count(prescribeddrugsindex) <> count(*) or min(prescribeddrugsindex) <> 0 or max(prescribeddrugsindex) <> count(*) - 1 or count(distinct prescribeddrugsindex) <> count(*)) x))::bigint as found, (select string_agg(n, ', ') from (select max(r.prescriptionid) n from prescribeddrugs t join prescription r on r.id = t.prescription group by t.prescription having count(t.prescribeddrugsindex) <> count(*) or min(t.prescribeddrugsindex) <> 0 or max(t.prescribeddrugsindex) <> count(*) - 1 or count(distinct t.prescribeddrugsindex) <> count(*) order by 1 limit 5) x) as details 
union all
select 47 as n, 'packages whose drug order has gaps' as item, ((select count(*) from (select parentpackage from packageddrugs where parentpackage is not null group by parentpackage having count(packageddrugsindex) <> count(*) or min(packageddrugsindex) <> 0 or max(packageddrugsindex) <> count(*) - 1 or count(distinct packageddrugsindex) <> count(*)) x))::bigint as found, (select string_agg(n, ', ') from (select max(k.packageid) n from packageddrugs t join package k on k.id = t.parentpackage group by t.parentpackage having count(t.packageddrugsindex) <> count(*) or min(t.packageddrugsindex) <> 0 or max(t.packageddrugsindex) <> count(*) - 1 or count(distinct t.packageddrugsindex) <> count(*) order by 1 limit 5) x) as details 
union all
select 48 as n, 'drug groups whose drug order has gaps' as item, ((select count(*) from (select regimen from regimendrugs where regimen is not null group by regimen having count(regimendrugsindex) <> count(*) or min(regimendrugsindex) <> 0 or max(regimendrugsindex) <> count(*) - 1 or count(distinct regimendrugsindex) <> count(*)) x))::bigint as found, (select string_agg(n, ', ') from (select max(g.regimenname) n from regimendrugs t join regimen g on g.id = t.regimen group by t.regimen having count(t.regimendrugsindex) <> count(*) or min(t.regimendrugsindex) <> 0 or max(t.regimendrugsindex) <> count(*) - 1 or count(distinct t.regimendrugsindex) <> count(*) order by 1 limit 5) x) as details 
) checks order by n;
